name: CI

on: [push, pull_request]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Build & test
        run: dotnet test --configuration Release --logger GitHubActions

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install NodeJS
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Pull dependencies
        run: npm ci --no-audit
        working-directory: ./MyFlickList.App

      - name: Build
        run: npm run build
        working-directory: ./MyFlickList.App
